### PR TITLE
Fix two syntax errors

### PR DESCRIPTION
**Pull request by fingolfin**
I wonder how this could slip through CI testing?

### CODE REVIEW

**Comment by fingolfin** [comment]
Aha, so apparently the syntax errors are not detected because they do not actually affect the test results -- I assume that means the function where they are in is not tested.

But also I think we may need a "strict mode" for GAP that turns syntax warnings into errors, so that CI tests can catch them... I've submitted a GAP feature request for that now

**Comment by ssiccha** [comment]
Ah, @maxhauck and @TristanPfersdorff, could you add tests for these code paths?

**Review by ssiccha — APPROVED** [review]

**Comment by ssiccha** [comment]
Maybe that's superseded by #20?

**Comment by fingolfin** [comment]
The issue is also fixed in #20 by @maxhauck, yes -- if that PR is merged quickly, this PR here can be closed. OTOH if that PR is likely to require more work, perhaps merge this PR and @maxhauck can rebase?

**Comment by ssiccha** [comment]
We're rebasing #20.

**Pull request merged**
