### PR TITLE
A bunch of changes

### PR DESCRIPTION
**Pull request by fingolfin**
- Cache GF(q) resp. GF(q^2)
- Replace two uses of MatrixByEntries
- Modernize some matrix code
- Fix a typo in a comment
- Simplify MatrixByEntries
- Refactor AntidiagonalMat

### CODE REVIEW

**Comment by fingolfin** [comment]
@ssiccha so, how to proceed? merge this or not?

**Comment by ssiccha** [comment]
I'm having lunch now. I'll try to rebase your PR onto master then. I think that's the easiest way for me to get this in.

**Comment by ssiccha** [comment]
See #30 for a rebased version. Some tests probably wont pass now.

**Comment by fingolfin** [comment]
@ssiccha tests pass now

**Review by ssiccha — APPROVED** [review]

**Comment by ssiccha** [comment]
Thanks :)

**Pull request merged**
